/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking.system;
import java.sql.*;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
import java.util.Base64;  
/**
 *
 * @author Navaneeth
 */
public class Withdraw extends javax.swing.JFrame {
Connection conn=null;
ResultSet RS=null;
PreparedStatement PST=null;
Statement stmt = null;

    /**
     * Creates new form Withdraw
     */
    public Withdraw(String para) {
        initComponents();
        conn=MysqlConnect.ConnecrDb();
        disp.setText(para);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        disp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        withdraw = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jToolBar3 = new javax.swing.JToolBar();
        account2 = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        update2 = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        withdraw2 = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        deposit2 = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        transaction2 = new javax.swing.JButton();
        jSeparator17 = new javax.swing.JToolBar.Separator();
        history2 = new javax.swing.JButton();
        jSeparator18 = new javax.swing.JToolBar.Separator();
        logout2 = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Acc.Holder : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Amount");

        withdraw.setText("Withdraw");
        withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Password");

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tekton Pro Cond", 1, 48)); // NOI18N
        jLabel5.setText("BANKING SYSTEM");

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel6.setText("WITHDRAW AMOUNT");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText(":");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText(":");

        jToolBar3.setRollover(true);

        account2.setText("Account Details");
        account2.setFocusable(false);
        account2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        account2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        account2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                account2ActionPerformed(evt);
            }
        });
        jToolBar3.add(account2);
        jToolBar3.add(jSeparator13);

        update2.setText("Update Password");
        update2.setFocusable(false);
        update2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        update2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        update2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update2ActionPerformed(evt);
            }
        });
        jToolBar3.add(update2);
        jToolBar3.add(jSeparator14);

        withdraw2.setText("Withdraw");
        withdraw2.setFocusable(false);
        withdraw2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        withdraw2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        withdraw2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdraw2ActionPerformed(evt);
            }
        });
        jToolBar3.add(withdraw2);
        jToolBar3.add(jSeparator15);

        deposit2.setText("Deposit");
        deposit2.setFocusable(false);
        deposit2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deposit2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deposit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deposit2ActionPerformed(evt);
            }
        });
        jToolBar3.add(deposit2);
        jToolBar3.add(jSeparator16);

        transaction2.setText("Transaction");
        transaction2.setFocusable(false);
        transaction2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transaction2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        transaction2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaction2ActionPerformed(evt);
            }
        });
        jToolBar3.add(transaction2);
        jToolBar3.add(jSeparator17);

        history2.setText("Transaction History");
        history2.setFocusable(false);
        history2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        history2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        history2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                history2ActionPerformed(evt);
            }
        });
        jToolBar3.add(history2);
        jToolBar3.add(jSeparator18);

        logout2.setText("Log Out");
        logout2.setFocusable(false);
        logout2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logout2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout2ActionPerformed(evt);
            }
        });
        jToolBar3.add(logout2);

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(withdraw)
                        .addGap(18, 18, 18)
                        .addComponent(reset)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disp, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(disp, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(11, 11, 11)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdraw)
                    .addComponent(reset))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawActionPerformed

        try{
            Statement st = conn.createStatement();
            int a = Integer.parseInt(amount.getText());
            String pass=password.getText();
            String user=disp.getText();
            Base64.Encoder encoder = Base64.getEncoder(); 
            String str = encoder.encodeToString(pass.getBytes());  
            String sql="SELECT balance FROM user where username='"+user+"' and encrypt='"+str+"'";
            
            PST=conn.prepareStatement(sql);
            RS=PST.executeQuery();
            

            if(RS.next()){
                String sqll="SELECT balance FROM user where balance>'"+a+"'";
            
            PST=conn.prepareStatement(sqll);
            RS=PST.executeQuery();
            if(RS.next()){
                int bal=Integer.parseInt(RS.getString("balance"));
                
                    int bala=bal-a;
                st.executeUpdate("UPDATE user SET balance='"+bala+"' WHERE username='"+user+"'");
                
                
                JOptionPane.showMessageDialog(null,"Amount Withdrawed");
            }else{
                JOptionPane.showMessageDialog(null,"Insufficient Balance"); 
            }
                
            }
                else{
                   JOptionPane.showMessageDialog(null,"Incorrect Password"); 
                }
                
            
                
                
            

        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_withdrawActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void account2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_account2ActionPerformed
        // TODO add your handling code here:
        String msg = disp.getText();
        new Account_details(msg).setVisible(true);
        Index i=new Index();
        i.setVisible(false);
        dispose();
    }//GEN-LAST:event_account2ActionPerformed

    private void update2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update2ActionPerformed
        // TODO add your handling code here:
        String msg = disp.getText();
        new Update(msg).setVisible(true);
        Index i=new Index();
        i.setVisible(false);
        dispose();
    }//GEN-LAST:event_update2ActionPerformed

    private void withdraw2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdraw2ActionPerformed
        // TODO add your handling code here:
        String msg = disp.getText();
        new Withdraw(msg).setVisible(true);
        Index i=new Index();
        i.setVisible(false);
        dispose();
    }//GEN-LAST:event_withdraw2ActionPerformed

    private void deposit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deposit2ActionPerformed
        // TODO add your handling code here:
        String msg = disp.getText();
        new Deposit(msg).setVisible(true);
        Index i=new Index();
        i.setVisible(false);
        dispose();
    }//GEN-LAST:event_deposit2ActionPerformed

    private void transaction2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaction2ActionPerformed
        // TODO add your handling code here:
        String msg = disp.getText();
        new Transfer(msg).setVisible(true);
        Index i=new Index();
        i.setVisible(false);
        dispose();
    }//GEN-LAST:event_transaction2ActionPerformed

    private void history2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_history2ActionPerformed
        // TODO add your handling code here:
        String msg = disp.getText();
        new Transaction_history(msg).setVisible(true);
        Index i=new Index();
        i.setVisible(false);
        dispose();
    }//GEN-LAST:event_history2ActionPerformed

    private void logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout2ActionPerformed
        // TODO add your handling code here:

        Index i=new Index();
        i.setVisible(false);
        dispose();
        Login l=new Login();
        l.setVisible(true);
    }//GEN-LAST:event_logout2ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        amount.setText("");
        password.setText("");
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdraw(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton account2;
    private javax.swing.JTextField amount;
    private javax.swing.JButton deposit2;
    private javax.swing.JLabel disp;
    private javax.swing.JButton history2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JToolBar.Separator jSeparator17;
    private javax.swing.JToolBar.Separator jSeparator18;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JButton logout2;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton reset;
    private javax.swing.JButton transaction2;
    private javax.swing.JButton update2;
    private javax.swing.JButton withdraw;
    private javax.swing.JButton withdraw2;
    // End of variables declaration//GEN-END:variables
}
